[theme]
primaryColor = "#E63946"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1FAEE"
textColor = "#1D3557"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
